### ISSUE TITLE
[Protection Enhancement] Solidshield Activation Wizard

### ISSUE THREAD

**Issue by Morlit55** [SabreTools/BinaryObjectScanner#348] opened 2024-12-29 19:59 UTC
An earlier name for the Solidshield Activation Manager found in http://redump.org/disc/63719/. Currently not detected by BoS but easily found inside the Solidshield dvm.dll file at 0x05A0D370 (included in drive below). 

https://drive.google.com/drive/folders/1GkIfi4gqpG2xN8i7qvFmqklLF9xhdUFZ?usp=drive_link

Also when scanning the TMP file (Also included) generated by the game's EXE containing the Activation Wizard, BoS will output "SolidShield EXE Wrapper Solidshield Technologies Ltd." which is presumably a bug.

**Comment by mnadareski** [comment] 2024-12-29 20:17
The former will be fixed soon. The latter is not a bug and comes from the section strings check.

**Closed** 2024-12-29 20:17 UTC
